version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/playwright:focal
    environment:
      NODE_ENV: development
    steps:
      - checkout

      - run:
          command: npm install

      - run:
          command: |
            npx playwright test
